// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Seven.Infrastructure.Persistence;

#nullable disable

namespace Seven.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SevenDbContext))]
    [Migration("20260831130000_DropBizDeviceDemo")]
    partial class DropBizDeviceDemo
    {
    }
}
