// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seven.Infrastructure.Persistence;

#nullable disable

namespace Seven.Infrastructure.Migrations
{
    [DbContext(typeof(SevenDbContext))]
    partial class SevenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Seven.Domain.Entities.Alarm.Sys_Alarm", b =>
                {
                    b.Property<int>("Alarm_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Alarm_Id"));

                    b.Property<DateTime?>("AckDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AckUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ExtraData")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Alarm_Id");

                    b.ToTable("Sys_Alarm", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Alarm.Sys_AlarmCode", b =>
                {
                    b.Property<int>("AlarmCode_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AlarmCode_Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<int>("Enable")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("AlarmCode_Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sys_AlarmCode", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Business.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("DeviceId");

                    b.ToTable("Device", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Business.SubDevice", b =>
                {
                    b.Property<int>("SubDeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubDeviceId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubDeviceCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SubDeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("SubDeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("SubDevice", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Core.Sys_TableColumn", b =>
                {
                    b.Property<int>("ColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ColumnId"));

                    b.Property<int?>("ColSize")
                        .HasColumnType("int");

                    b.Property<string>("ColumnCNName")
                        .HasColumnType("longtext");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ColumnType")
                        .HasColumnType("longtext");

                    b.Property<int?>("ColumnWidth")
                        .HasColumnType("int");

                    b.Property<string>("Columnformat")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("DropNo")
                        .HasColumnType("longtext");

                    b.Property<int?>("EditColNo")
                        .HasColumnType("int");

                    b.Property<int?>("EditRowNo")
                        .HasColumnType("int");

                    b.Property<string>("EditType")
                        .HasColumnType("longtext");

                    b.Property<bool>("Editable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Enable")
                        .HasColumnType("int");

                    b.Property<int?>("IsColumnData")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IsDisplay")
                        .HasColumnType("int");

                    b.Property<int?>("IsImage")
                        .HasColumnType("int");

                    b.Property<bool>("IsKey")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IsNull")
                        .HasColumnType("int");

                    b.Property<int?>("IsReadDataset")
                        .HasColumnType("int");

                    b.Property<int?>("Maxlength")
                        .HasColumnType("int");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("Script")
                        .HasColumnType("longtext");

                    b.Property<int?>("SearchColNo")
                        .HasColumnType("int");

                    b.Property<int?>("SearchRowNo")
                        .HasColumnType("int");

                    b.Property<string>("SearchType")
                        .HasColumnType("longtext");

                    b.Property<int?>("Sortable")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasColumnType("longtext");

                    b.Property<int>("Table_Id")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("ColumnId");

                    b.HasIndex("Table_Id");

                    b.ToTable("Sys_TableColumn", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Core.Sys_TableDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("ChildTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CnName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ForeignKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MasterKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("ParentTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("DetailId");

                    b.HasIndex("ParentTable", "ChildTable", "ForeignKey")
                        .IsUnique();

                    b.ToTable("Sys_TableDetail", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Core.Sys_TableInfo", b =>
                {
                    b.Property<int>("Table_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Table_Id"));

                    b.Property<string>("CnName")
                        .HasColumnType("longtext");

                    b.Property<string>("ColumnCNName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("DBServer")
                        .HasColumnType("longtext");

                    b.Property<string>("DataTableType")
                        .HasColumnType("longtext");

                    b.Property<string>("DetailName")
                        .HasColumnType("longtext");

                    b.Property<string>("EditorType")
                        .HasColumnType("longtext");

                    b.Property<int?>("Enable")
                        .HasColumnType("int");

                    b.Property<string>("ExpressField")
                        .HasColumnType("longtext");

                    b.Property<string>("FolderName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<string>("Namespace")
                        .HasColumnType("longtext");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("SortName")
                        .HasColumnType("longtext");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TableTrueName")
                        .HasColumnType("longtext");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("UploadField")
                        .HasColumnType("longtext");

                    b.HasKey("Table_Id");

                    b.ToTable("Sys_TableInfo", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Flow.Sys_WorkFlow", b =>
                {
                    b.Property<int>("WorkFlow_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkFlow_Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<byte?>("Enable")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WorkTable")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkTableKey")
                        .HasColumnType("longtext");

                    b.HasKey("WorkFlow_Id");

                    b.ToTable("Sys_WorkFlow", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Flow.Sys_WorkFlowStep", b =>
                {
                    b.Property<int>("WorkStepFlow_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkStepFlow_Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<int?>("StepType")
                        .HasColumnType("int");

                    b.Property<string>("StepValue")
                        .HasColumnType("longtext");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("WorkFlow_Id")
                        .HasColumnType("int");

                    b.HasKey("WorkStepFlow_Id");

                    b.HasIndex("WorkFlow_Id");

                    b.ToTable("Sys_WorkFlowStep", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Flow.Sys_WorkFlowTable", b =>
                {
                    b.Property<int>("WorkFlowTable_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkFlowTable_Id"));

                    b.Property<int>("AuditStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<int?>("CurrentStepId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("WorkFlow_Id")
                        .HasColumnType("int");

                    b.Property<string>("WorkTable")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkTableKey")
                        .HasColumnType("longtext");

                    b.HasKey("WorkFlowTable_Id");

                    b.ToTable("Sys_WorkFlowTable", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Flow.Sys_WorkFlowTableAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditStatus")
                        .HasColumnType("int");

                    b.Property<string>("AuditUser")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("WorkFlowTable_Id")
                        .HasColumnType("int");

                    b.Property<int>("WorkStepFlow_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sys_WorkFlowTableAuditLog", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Flow.Sys_WorkFlowTableStep", b =>
                {
                    b.Property<int>("Sys_WorkFlowTableStep_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Sys_WorkFlowTableStep_Id"));

                    b.Property<DateTime?>("AuditDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AuditStatus")
                        .HasColumnType("int");

                    b.Property<int?>("AuditUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("WorkFlowTable_Id")
                        .HasColumnType("int");

                    b.Property<int>("WorkStepFlow_Id")
                        .HasColumnType("int");

                    b.HasKey("Sys_WorkFlowTableStep_Id");

                    b.ToTable("Sys_WorkFlowTableStep", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Form.FormCollectionObject", b =>
                {
                    b.Property<int>("FormCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FormCollectionId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("FormData")
                        .HasColumnType("longtext");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<string>("Submitter")
                        .HasColumnType("longtext");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("FormCollectionId");

                    b.ToTable("FormCollectionObject", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Form.FormDesignOptions", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FormId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<byte?>("Enable")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("FormHtml")
                        .HasColumnType("longtext");

                    b.Property<string>("FormOptions")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FormId");

                    b.ToTable("FormDesignOptions", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.News.App_News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<byte?>("Enable")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("App_News", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Quartz.Sys_QuartzLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<int>("ElapsedMs")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<string>("ResponseContent")
                        .HasColumnType("longtext");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.ToTable("Sys_QuartzLog", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.Quartz.Sys_QuartzOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte?>("Enable")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("GroupName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sys_QuartzOptions", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("longtext");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte?>("Enable")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.ToTable("Sys_Department", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_Dictionary", b =>
                {
                    b.Property<int>("Dic_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Dic_ID"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("DicName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DicNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte?>("Enable")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Dic_ID");

                    b.ToTable("Sys_Dictionary", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_DictionaryList", b =>
                {
                    b.Property<int>("DicList_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DicList_ID"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("DicName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DicValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Dic_ID")
                        .HasColumnType("int");

                    b.Property<byte?>("Enable")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("DicList_ID");

                    b.HasIndex("Dic_ID");

                    b.ToTable("Sys_DictionaryList", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("ExceptionInfo")
                        .HasColumnType("longtext");

                    b.Property<string>("IPAddress")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LogType")
                        .HasColumnType("longtext");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<string>("RequestParameter")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseParameter")
                        .HasColumnType("longtext");

                    b.Property<int?>("ServiceTime")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<int?>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sys_Log", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_Menu", b =>
                {
                    b.Property<int>("Menu_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Menu_Id"));

                    b.Property<string>("Auth")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<byte?>("Enable")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("MenuType")
                        .HasColumnType("int");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasColumnType("longtext");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Menu_Id");

                    b.ToTable("Sys_Menu", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_Role", b =>
                {
                    b.Property<int>("Role_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Role_Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<int>("DataScope")
                        .HasColumnType("int");

                    b.Property<int?>("Dept_Id")
                        .HasColumnType("int");

                    b.Property<byte?>("Enable")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Role_Id");

                    b.ToTable("Sys_Role", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_RoleAuth", b =>
                {
                    b.Property<int>("Auth_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Auth_Id"));

                    b.Property<string>("AuthValue")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Menu_Id")
                        .HasColumnType("int");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int>("Role_Id")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Auth_Id");

                    b.HasIndex("Role_Id");

                    b.ToTable("Sys_RoleAuth", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Enable")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TenantId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sys_Tenant", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("DeptIds")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<byte>("Enable")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("HeadImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastModifyPwdDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<bool>("MustResetPassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleName")
                        .HasColumnType("longtext");

                    b.Property<int>("Role_Id")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserTrueName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("User_Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Sys_User", (string)null);
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_UserDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sys_UserDepartment", (string)null);
                });

            modelBuilder.Entity("Seven.Infrastructure.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateId")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("Error")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Seven.Domain.Entities.Business.SubDevice", b =>
                {
                    b.HasOne("Seven.Domain.Entities.Business.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Seven.Domain.Entities.Core.Sys_TableColumn", b =>
                {
                    b.HasOne("Seven.Domain.Entities.Core.Sys_TableInfo", null)
                        .WithMany("TableColumns")
                        .HasForeignKey("Table_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Seven.Domain.Entities.Flow.Sys_WorkFlowStep", b =>
                {
                    b.HasOne("Seven.Domain.Entities.Flow.Sys_WorkFlow", "WorkFlow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkFlow_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkFlow");
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_DictionaryList", b =>
                {
                    b.HasOne("Seven.Domain.Entities.System.Sys_Dictionary", "Dictionary")
                        .WithMany("DictionaryLists")
                        .HasForeignKey("Dic_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_RoleAuth", b =>
                {
                    b.HasOne("Seven.Domain.Entities.System.Sys_Role", "Role")
                        .WithMany("RoleAuths")
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Seven.Domain.Entities.Core.Sys_TableInfo", b =>
                {
                    b.Navigation("TableColumns");
                });

            modelBuilder.Entity("Seven.Domain.Entities.Flow.Sys_WorkFlow", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_Dictionary", b =>
                {
                    b.Navigation("DictionaryLists");
                });

            modelBuilder.Entity("Seven.Domain.Entities.System.Sys_Role", b =>
                {
                    b.Navigation("RoleAuths");
                });
#pragma warning restore 612, 618
        }
    }
}
